#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ArcTouchPark.Droid.Resource", IsApplication=true)]

namespace ArcTouchPark.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int attachment = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bullet = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int disclosure_chevron = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int doc_category_construction_lg = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int doc_category_construction_sm = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int doc_category_favorites_lg = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int doc_category_favorites_sm = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int doc_category_handbook_lg = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int doc_category_handbook_sm = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int doc_category_hoa_lg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int doc_category_hoa_sm = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int doc_category_lennar_care_lg = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int doc_category_lennar_care_sm = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int doc_category_mortgage_lg = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int doc_category_mortgage_sm = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int doc_category_other_lg = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int doc_category_other_sm = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int doc_category_purchase_lg = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int doc_category_purchase_sm = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int doc_category_service_request_lg = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int doc_category_service_request_sm = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int doc_category_spec_sm = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int doc_category_title_lg = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int doc_category_title_sm = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int doc_category_warranty_lg = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int doc_category_warranty_sm = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int document_lg = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int documents_group_lg = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int dot_indicator = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int dot_indicator_active = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int favorite = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int favorite_navbar = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int favorited = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int favorited_navbar = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int forward_circle_arrow = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int icon = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int info_i = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int line_pattern = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int login_bg = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int menu = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int menu_circle_mask = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int menu_lennar_logo = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int no_image = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int right_chevron = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int share = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int splash = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int splash_drawable = 2130837550;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
	}
}
#pragma warning restore 1591
